# use the alpine base image
FROM ubuntu:14.04
MAINTAINER Andreas Galanomatis

RUN mkdir -p /app
RUN mkdir -p /app/certs
WORKDIR /app

# copy the binary
ADD ./ngrokd /app

RUN chown root /app/ngrokd && chmod 700 /app/ngrokd

CMD /app/bin/ngrokd -domain $NGROK_DOMAIN -log /var/log/ngrokd.log