# use the alpine base image
FROM alpine:3.3
MAINTAINER Andreas Galanomatis

RUN mkdir -p /app
RUN mkdir -p /app/certs
WORKDIR /app

# copy the binary
ADD ./ngrokd /app

# RUN chown root /app/ngrokd && chmod 700 /app/ngrokd

CMD /app/ngrokd -domain="$NGROK_DOMAIN"