---
services:
  ngrok:
    git_url: http://github.com/agalanom/ngrok.git
    git_branch: master
    use_habitus: true
    use_habitus_step: runtime
    volumes:
    - "/var/ngrok:/var/ngrok"
    ports:
    - container: 80
      http: 80
      https: 443
    - container: 4443
      tcp: 4443
